var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+b++,d)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();
var _typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};function _toConsumableArray(a){if(Array.isArray(a)){for(var b=0,d=Array(a.length);b<a.length;b++)d[b]=a[b];return d}return Array.from(a)}
(function(){window.attachEvent&&!window.addEventListener||function(a){function b(l){if(d[l])return d[l].exports;var p=d[l]={i:l,l:!1,exports:{}};a[l].call(p.exports,p,p.exports,b);p.l=!0;return p.exports}var d={};b.m=a;b.c=d;b.i=function(a){return a};b.d=function(a,p,m){b.o(a,p)||Object.defineProperty(a,p,{configurable:!1,enumerable:!0,get:m})};b.n=function(a){var p=a&&a.__esModule?function(){return a["default"]}:function(){return a};b.d(p,"a",p);return p};b.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,
b)};b.p="";return b(b.s=6)}([function(a,b,d){(function(b){(function(d){function m(){}function p(c,g){return function(){c.apply(g,arguments)}}function h(c){if("object"!==_typeof(this))throw new TypeError("Promises must be constructed via new");if("function"!==typeof c)throw new TypeError("not a function");this._state=0;this._handled=!1;this._value=void 0;this._deferreds=[];f(c,this)}function k(c,g){for(;3===c._state;)c=c._value;0===c._state?c._deferreds.push(g):(c._handled=!0,h._immediateFn(function(){var a=
1===c._state?g.onFulfilled:g.onRejected;if(null===a)(1===c._state?q:e)(g.promise,c._value);else{try{var b=a(c._value)}catch(v){e(g.promise,v);return}q(g.promise,b)}}))}function q(c,a){try{if(a===c)throw new TypeError("A promise cannot be resolved with itself.");if(a&&("object"===("undefined"===typeof a?"undefined":_typeof(a))||"function"===typeof a)){var g=a.then;if(a instanceof h){c._state=3;c._value=a;l(c);return}if("function"===typeof g){f(p(g,a),c);return}}c._state=1;c._value=a;l(c)}catch(u){e(c,
u)}}function e(c,a){c._state=2;c._value=a;l(c)}function l(c){2===c._state&&0===c._deferreds.length&&h._immediateFn(function(){c._handled||h._unhandledRejectionFn(c._value)});for(var a=0,n=c._deferreds.length;a<n;a++)k(c,c._deferreds[a]);c._deferreds=null}function r(c,a,n){this.onFulfilled="function"===typeof c?c:null;this.onRejected="function"===typeof a?a:null;this.promise=n}function f(c,a){var n=!1;try{c(function(c){n||(n=!0,q(a,c))},function(c){n||(n=!0,e(a,c))})}catch(u){n||(n=!0,e(a,u))}}var w=
setTimeout;h.prototype["catch"]=function(c){return this.then(null,c)};h.prototype.then=function(c,a){var n=new this.constructor(m);k(this,new r(c,a,n));return n};h.all=function(c){var a=Array.prototype.slice.call(c);return new h(function(c,b){function n(m,g){try{if(g&&("object"===("undefined"===typeof g?"undefined":_typeof(g))||"function"===typeof g)){var d=g.then;if("function"===typeof d){d.call(g,function(c){n(m,c)},b);return}}a[m]=g;0===--f&&c(a)}catch(A){b(A)}}if(0===a.length)return c([]);for(var f=
a.length,m=0;m<a.length;m++)n(m,a[m])})};h.resolve=function(c){return c&&"object"===("undefined"===typeof c?"undefined":_typeof(c))&&c.constructor===h?c:new h(function(a){a(c)})};h.reject=function(c){return new h(function(a,b){b(c)})};h.race=function(c){return new h(function(a,b){for(var m=0,n=c.length;m<n;m++)c[m].then(a,b)})};h._immediateFn="function"===typeof b&&function(a){b(a)}||function(a){w(a,0)};h._unhandledRejectionFn=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",
a)};h._setImmediateFn=function(a){h._immediateFn=a};h._setUnhandledRejectionFn=function(a){h._unhandledRejectionFn=a};"undefined"!==typeof a&&a.exports?a.exports=h:d.Promise||(d.Promise=h)})(this)}).call(b,d(4).setImmediate)},function(a,b,d){b.a="function"==typeof fetch?fetch:function(a,b){b=b||{};return new Promise(function(m,d){function h(){var a=[],b=[],m={},f;k.getAllResponseHeaders().replace(/^(.*?):\s*([\s\S]*?)$/gm,function(d,c,g){a.push(c=c.toLowerCase());b.push([c,g]);f=m[c];m[c]=f?f+","+
g:g});return{ok:1==(k.status/200|0),status:k.status,statusText:k.statusText,url:k.responseURL,clone:h,text:function(){return Promise.resolve(k.responseText)},json:function(){return Promise.resolve(k.responseText).then(JSON.parse)},xml:function(){return Promise.resolve(k.responseXML)},blob:function(){return Promise.resolve(new Blob([k.response]))},headers:{keys:function(){return a},entries:function(){return b},get:function(a){return m[a.toLowerCase()]},has:function(a){return a.toLowerCase()in m}}}}
var k=new XMLHttpRequest;k.open(b.method||"get",a);for(var l in b.headers)k.setRequestHeader(l,b.headers[l]);k.withCredentials="include"==b.credentials;k.onload=function(){m(h())};k.onerror=d;k.send(b.body)})}},function(a,b){function d(){throw Error("setTimeout has not been defined");}function l(){throw Error("clearTimeout has not been defined");}function p(a){if(t===setTimeout)return setTimeout(a,0);if((t===d||!t)&&setTimeout)return t=setTimeout,setTimeout(a,0);try{return t(a,0)}catch(u){try{return t.call(null,
a,0)}catch(v){return t.call(this,a,0)}}}function m(a){if(r===clearTimeout)return clearTimeout(a);if((r===l||!r)&&clearTimeout)return r=clearTimeout,clearTimeout(a);try{return r(a)}catch(u){try{return r.call(null,a)}catch(v){return r.call(this,a)}}}function y(){w&&c&&(w=!1,c.length?f=c.concat(f):g=-1,f.length&&h())}function h(){if(!w){var a=p(y);w=!0;for(var b=f.length;b;){c=f;for(f=[];++g<b;)c&&c[g].run();g=-1;b=f.length}c=null;w=!1;m(a)}}function k(a,c){this.fun=a;this.array=c}function q(){}var e=
a.exports={};try{var t="function"===typeof setTimeout?setTimeout:d}catch(n){t=d}try{var r="function"===typeof clearTimeout?clearTimeout:l}catch(n){r=l}var f=[],w=!1,c,g=-1;e.nextTick=function(a){var c=Array(arguments.length-1);if(1<arguments.length)for(var b=1;b<arguments.length;b++)c[b-1]=arguments[b];f.push(new k(a,c));1!==f.length||w||p(h)};k.prototype.run=function(){this.fun.apply(null,this.array)};e.title="browser";e.browser=!0;e.env={};e.argv=[];e.version="";e.versions={};e.on=q;e.addListener=
q;e.once=q;e.off=q;e.removeListener=q;e.removeAllListeners=q;e.emit=q;e.prependListener=q;e.prependOnceListener=q;e.listeners=function(a){return[]};e.binding=function(a){throw Error("process.binding is not supported");};e.cwd=function(){return"/"};e.chdir=function(a){throw Error("process.chdir is not supported");};e.umask=function(){return 0}},function(a,b,d){(function(a,b){(function(a,d){function m(a){delete g[a]}function k(a){if(n)setTimeout(k,0,a);else{var c=g[a];if(c){n=!0;try{var b=c.callback,
f=c.args;switch(f.length){case 0:b();break;case 1:b(f[0]);break;case 2:b(f[0],f[1]);break;case 3:b(f[0],f[1],f[2]);break;default:b.apply(d,f)}}finally{m(a),n=!1}}}}function l(){v=function(a){b.nextTick(function(){k(a)})}}function e(){if(a.postMessage&&!a.importScripts){var c=!0,b=a.onmessage;a.onmessage=function(){c=!1};a.postMessage("","*");a.onmessage=b;return c}}function p(){var c="setImmediate$"+Math.random()+"$",b=function(b){b.source===a&&"string"===typeof b.data&&0===b.data.indexOf(c)&&k(+b.data.slice(c.length))};
a.addEventListener?a.addEventListener("message",b,!1):a.attachEvent("onmessage",b);v=function(b){a.postMessage(c+b,"*")}}function r(){var a=new MessageChannel;a.port1.onmessage=function(a){k(a.data)};v=function(c){a.port2.postMessage(c)}}function f(){var a=u.documentElement;v=function(c){var b=u.createElement("script");b.onreadystatechange=function(){k(c);b.onreadystatechange=null;a.removeChild(b);b=null};a.appendChild(b)}}function w(){v=function(a){setTimeout(k,0,a)}}if(!a.setImmediate){var c=1,
g={},n=!1,u=a.document,v,x=Object.getPrototypeOf&&Object.getPrototypeOf(a);x=x&&x.setTimeout?x:a;"[object process]"==={}.toString.call(a.process)?l():e()?p():a.MessageChannel?r():u&&"onreadystatechange"in u.createElement("script")?f():w();x.setImmediate=function(a){"function"!==typeof a&&(a=new Function(""+a));for(var b=Array(arguments.length-1),f=0;f<b.length;f++)b[f]=arguments[f+1];g[c]={callback:a,args:b};v(c);return c++};x.clearImmediate=m}})("undefined"===typeof self?"undefined"===typeof a?this:
a:self)}).call(b,d(5),d(2))},function(a,b,d){function l(a,b){this._id=a;this._clearFn=b}var p=Function.prototype.apply;b.setTimeout=function(){return new l(p.call(setTimeout,window,arguments),clearTimeout)};b.setInterval=function(){return new l(p.call(setInterval,window,arguments),clearInterval)};b.clearTimeout=b.clearInterval=function(a){a&&a.close()};l.prototype.unref=l.prototype.ref=function(){};l.prototype.close=function(){this._clearFn.call(window,this._id)};b.enroll=function(a,b){clearTimeout(a._idleTimeoutId);
a._idleTimeout=b};b.unenroll=function(a){clearTimeout(a._idleTimeoutId);a._idleTimeout=-1};b._unrefActive=b.active=function(a){clearTimeout(a._idleTimeoutId);var b=a._idleTimeout;0<=b&&(a._idleTimeoutId=setTimeout(function(){a._onTimeout&&a._onTimeout()},b))};d(3);b.setImmediate=setImmediate;b.clearImmediate=clearImmediate},function(a,b){var d=function(){return this}();try{d=d||Function("return this")()||(0,eval)("this")}catch(l){"object"===("undefined"===typeof window?"undefined":_typeof(window))&&
(d=window)}a.exports=d},function(a,b,d){Object.defineProperty(b,"__esModule",{value:!0});a=d(0);a=d.n(a);var l=d(1);window.Promise||(window.Promise=a.a);window.fetch||(window.fetch=l.a);(function(){try{var a=function(a,d,c,g,n,h){e(a);var f={isFinal:!0};f.formData=y(d);b(n,f,h,function(){if(a)e(c);else{var b=document.createElement("p");b.className="foform-success";var f=document.createTextNode("Ch\u00e2n th\u00e0nh c\u00e1m \u01a1n th\u00f4ng tin li\u00ean h\u1ec7 c\u1ee7a b\u1ea1n. Ch\u00fang t\u00f4i s\u1ebd tr\u1ea3 l\u1eddi b\u1ea1n trong th\u1eddi gian s\u1edbm nh\u1ea5t!");
b.appendChild(f);d.parentElement.replaceChild(b,d)}},function(){e(g)})},b=function(a,b,c,d,e){!a.submissionUuid&&a.createSubmissionSent?a.pendingSubmissionData.push(b):a.submissionUuid?k(b,c,a.submissionUuid).then(function(a){d()})["catch"](function(a){e()}):(a.createSubmissionSent=!0,a.submissionUuid=q()+q()+"-"+q()+"-"+q()+"-"+q()+"-"+q()+q()+q(),b.uuid=a.submissionUuid,h(b,c).then(function(a){return a.json()}).then(function(b){d();for(b=0;b<a.pendingSubmissionData.length;b+=1)k(a.pendingSubmissionData[b],
c,a.submissionUuid).then(function(a){})["catch"](function(a){e()})})["catch"](function(a){e()}))},y=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];"submit"!==d.type&&b.push({name:d.name,value:d.value})}return b},h=function(a,b){console.log("Creating the submission");return d.i(l.a)(r+"/forms/"+b+"/submissions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(a)}).then(function(a){if(a.ok)return a;throw Error("Failed to create submission");})},k=function(a,b,
c){return d.i(l.a)(r+"/submissions/"+c,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(a)}).then(function(a){if(a.ok)return a;throw Error("error updating submission");})},q=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)},e=function(a){if("function"===typeof window[a])window[a]()},t=!!document.querySelectorAll('[foform-is-dev="true"]').length;console.log("Development mode is",t);var r="";r=t?"https://dev-api.foform.com":"https://api.foform.com";
document.addEventListener("DOMContentLoaded",function(){var d={submissionUuid:null,createSubmissionSent:!1,pendingSubmissionData:[]},e=document.getElementsByTagName("form"),c=/api.foform.com\/forms\/.*\/submissions/;console.log("Forms on page",e);e=[].concat(_toConsumableArray(e)).filter(function(a){return c.test(a.action)});var g=!0,h=!1,k=void 0;try{var l=function(){var c=p.value,e=c.attributes.action.value.match(/forms\/(.*)\/submissions/)[1];c.addEventListener("submit",function(b){b.preventDefault();
b=c.getAttribute("data-on-submit");var f=c.getAttribute("data-on-success"),g=c.getAttribute("data-on-error"),h=c.getAttribute("data-is-valid");"function"===typeof window[h]?window[h]()?a(b,c,f,g,d,e):console.log("Validation error"):a(b,c,f,g,d,e)},!1);c.addEventListener("blur",function(a){"submit"!==a.srcElement.type&&(a={isFinal:!1},a.formData=y(c),b(d,a,e,function(){}))},!0)};$jscomp.initSymbol();$jscomp.initSymbolIterator();for(var m=e[Symbol.iterator](),p;!(g=(p=m.next()).done);g=!0)l()}catch(z){h=
!0,k=z}finally{try{!g&&m["return"]&&m["return"]()}finally{if(h)throw k;}}})}catch(f){console.log(f)}})()}])})();